# ConfiguraÃ§Ã£o do Starship

# Ordem dos mÃ³dulos no prompt principal (uma linha sÃ³)
format = """\
$username$hostname\
$directory\
$git_branch$git_status$git_state$git_commit$git_metrics\
$python$nodejs$java$php$lua\
$docker_context$container$azure\
$cmd_duration\
\n$character"""

# Adiciona uma nova linha entre os prompts do shell (recomendado TRUE para melhor visualizaÃ§Ã£o)
add_newline = true

# Timeout para comandos (em milissegundos)
command_timeout = 10000

# Timeout para verificaÃ§Ã£o de arquivos no diretÃ³rio atual (em milissegundos)
scan_timeout = 10

# ConfiguraÃ§Ãµes do caractere de prompt
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red) "

# ConfiguraÃ§Ãµes do pacote
[package]
format = " via [ğŸ $version](208 bold)"
disabled = false

# ConfiguraÃ§Ãµes do nome de usuÃ¡rio
[username]
format = "[$user](bold white) "
disabled = false
show_always = false

# ConfiguraÃ§Ãµes do nome do host (somente SSH)
[hostname]
ssh_only = true
format = "on [$hostname](bold yellow)"
disabled = false

# ConfiguraÃ§Ãµes da duraÃ§Ã£o do comando
[cmd_duration]
format = "underwent [$duration](bold yellow)"
min_time = 500

# ConfiguraÃ§Ãµes do diretÃ³rio
[directory]
format = "at [$path ](bold cyan)[$read_only](bold red)"
truncation_length = 1
truncation_symbol = "â€¦/"
home_symbol = "ó°‹œ ~ "
read_only = "ğŸ”"
use_logical_path = true
disabled = false

# ConfiguraÃ§Ãµes do branch Git
[git_branch]
symbol = "î‚  "
format = " on [$symbol$branch (:$remote_branch)](bold purple)"
truncation_length = 7
truncation_symbol = "â€¦/"
only_attached = false
disabled = false

# ConfiguraÃ§Ãµes do status Git
[git_status]
format = '([\( $all_status$ahead_behind\)]($style) )'
style = 'bold cyan'
conflicted = '[ïª conflito=${count}](red) '
up_to_date = '[ó°˜½ atualizado](green) '
untracked = '[ó°‹— nÃ£o rastreado=${count}](red) '
modified = '[ó°›¿ modificado=${count}](yellow) '
staged = '[ó°— em stage=${count}](green) '
renamed = '[ó±¸ renomeado=${count}](yellow) '
deleted = '[ó°¶ excluÃ­do=${count}](red) '
stashed = '[ïŠ‹ armazenado=${count}](green) '
ahead = '[â‡¡ Ã  frente=${count}](cyan)'
behind = '[â‡£ atrÃ¡s=${count}](red)'
diverged = '[â‡• divergente: Ã  frente=${ahead_count} atrÃ¡s=${behind_count}](purple)'
disabled = false

# MÃ©tricas do Git
[git_metrics]
format = "([+$added](bold green))([-$deleted](bold red))"
ignore_submodules = false
disabled = false

# Estado do Git
[git_state]
format = "([$state($progress_current/$progress_total)](bold yellow))"
cherry_pick = "[ğŸ’ PICKING](bold red)"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
disabled = false

# Commit Git
[git_commit]
format = "([$hash$tag](bold green))"
commit_hash_length = 7
tag_symbol = "ğŸ· "
disabled = false

# Python
[python]
format = " via [${symbol}${pyenv_prefix}(${version} )($virtualenv )](bold green)"
symbol = "ğŸ "
pyenv_version_name = true
python_binary = ["python", "python3", "python2"]
disabled = false

# Node.js
[nodejs]
format = " via [$symbol$version](bold green)"
version_format = "v${raw}"
symbol = "îœ˜ "
detect_files = ["package.json", ".node-version", "!bunfig.toml", "!bun.lockb"]
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts"]
detect_folders = ["node_modules"]
not_capable_style = "bold red"
disabled = false

# Java
[java]
format = " via [${symbol}${version}](red dimmed)"
detect_extensions = ["java", "class", "gradle", "jar", "cljs", "cljc"]
detect_files = ["pom.xml", "build.gradle.kts", "build.sbt", ".java-version", "deps.edn", "project.clj", "build.boot", ".sdkmanrc"]
symbol = "â˜• "
disabled = false

# Lua
[lua]
format = " via [$symbol$version](bold blue)"
version_format = "v${raw}"
symbol = "ğŸŒ™ "
detect_extensions = ["lua"]
detect_files = [".lua-version"]
detect_folders = ["lua"]
lua_binary = "lua"

# PHP
[php]
format = " via [ğŸ”¹ $version](147 bold)"
version_format = "v${raw}"
symbol = "ğŸ˜ "
detect_extensions = ["php"]

# Azure
[azure]
format = " on [$symbol$subscription$username](blue bold)"
symbol = "ó° … "
disabled = false

# Container
[container]
format = "[$symbol [$name]](red bold dimmed)"
symbol = "â¬¢"
disabled = false

# Docker Context
[docker_context]
format = " via [$symbol$context](blue bold)"
symbol = "ğŸ‹ "
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yml", "Dockerfile"]
disabled = false

